---
namespace: "veeamhub"
name: "veeam"
version: "2.3.4"
readme: "readme_galaxy.md"
authors:
  - "Chris Arceneaux (https://www.arsano.ninja/)"
  - "Markus Kraus (https://mycloudrevolution.com/)"
description: Administer Veeam Software
license_file: "LICENSE"
tags:
  - application
  - veeam
  - availability
  - suite
  - backup
  - replication
  - enterprise
  - manager
  - one
  - server
  - system
  - backup
  - vbr
  - vem
  - em
dependencies:
  ansible.windows: '3.3.0'
  community.windows: '3.1.0'
repository: "https://github.com/VeeamHub/veeam-ansible"
issues: "https://github.com/VeeamHub/veeam-ansible/issues"
