---
# one_client_upgrade tasks file for veeamhub.veeam_vas
- name: Checking to see if Veeam ONE Monitor Client is installed
  veeam_software_check:
    name: "Veeam ONE Monitor Client"
  register: software
- name: Is Veeam ONE Monitor Client installed?
  fail:
    msg: "Veeam ONE Monitor Client must be installed on this server in order to upgrade it."
  when: not (software.installed | bool)
- name: Including version-specific variables
  include_vars:
    file: "vars/one_v{{ version }}.yml"

# PRE-UPGRADE TASKS
- name: Veeam ONE ISO Tasks
  include_tasks: mount_iso.yml
- name: Print Upgrade Configuration
  debug:
    msg:
      - "ISO Drive Letter: '{{ source }}'"
      - "Upgrade Logs Folder: '{{ destination }}logs'"
      - "Version: {{ version }}"
      - "Download ISO?: {{ iso_download }}"
      - "ISO Source: {{ iso_url }}"
      - "ISO File Destination: {{ destination }}{{ destination_iso_file }}"
      - "Veeam ONE Server: {{ one_server }}"
- name: Create logs directory
  ansible.windows.win_file:
    path: "{{ destination }}logs"
    state: directory
- name: .NET Framework
  include_tasks: install_net_framework.yml
- name: Install XML Parser
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\msxml6_x64.msi"
    state: present
- name: Install Microsoft Visual C++ Redistributable
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\vc_redist.x64.exe"
    product_id: Install C++ Framework
    state: present
    arguments: '/install /quiet /norestart /log "{{ destination }}logs\\vc_redist.x64.log"'
  ignore_errors: yes
  when: version | int >= 12

# UPGRADING VEEAM SOFTWARE
- name: Upgrade ONE Monitor Client (v12+)
  ansible.windows.win_package:
    path: "{{ source }}Monitor\\VeeamONE.Monitor.Client.x64.msi"
    state: present
    arguments: '/L*v "{{ destination }}logs\VeeamONE.Monitor.Client.x64.log" ACCEPT_THIRDPARTY_LICENSES=1 ACCEPT_EULA=1 ACCEPT_LICENSING_POLICY=1 ACCEPT_REQUIRED_SOFTWARE=1 VM_CLN_SERVER_NAME="{{ one_server }}"'
  when: version | int >= 12
- name: Upgrade ONE Monitor Client (v11-)
  ansible.windows.win_package:
    path: "{{ source }}Monitor\\VeeamONE.Monitor.Client.x64.msi"
    state: present
    arguments: '/L*v "{{ destination }}logs\VeeamONE.Monitor.Client.x64.log" ACCEPT_THIRDPARTY_LICENSES=1 ACCEPT_EULA=1 VM_CLN_SERVER_NAME="{{ one_server }}"'
  when: version | int <= 11
- name: Finding file(s) in '{{ source }}Updates' directory
  ansible.windows.win_find:
    paths: "{{ source }}Updates"
    recurse: no
    file_type: file
  ignore_errors: yes
  register: file
- name: Does Veeam ONE need to be patched?
  set_fact:
    patch: "{{ file.matched }}"
- name: Setting patch filename
  set_fact:
    patch_file: "{{ file.files[0].filename }}"
  when: patch | bool
- name: Including Veeam ONE patch tasks
  include_tasks: one_patch.yml
  when: patch | bool

# POST-UPGRADE TASKS
- name: Unmount ISO
  community.windows.win_disk_image:
    image_path: "{{ destination }}{{ destination_iso_file }}"
    state: absent
