---
# one_install_pretasks tasks file for veeamhub.veeam_vas

# PRE-INSTALL TASKS
- name: Create logs directory
  ansible.windows.win_file:
    path: "{{ destination }}logs"
    state: directory
- name: Create Local Veeam ONE Service Account User
  ansible.windows.win_user:
    name: "{{ one_username }}"
    password: "{{ one_password }}"
    password_never_expires: yes
    state: present
    groups:
      - Administrators
  when:
    - one_create_service_account | bool
    - one_username.find("\\") == -1 # skips account creation if domain account is specified
- name: Install System CLR Types
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\SQLSysClrTypes.msi"
    state: present
- name: Install Shared management objects
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\SharedManagementObjects.msi"
    state: present
- name: Install SQL Native Client
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\sqlncli.msi"
    state: present
    arguments: "IACCEPTSQLNCLILICENSETERMS=YES"
- name: Install Microsoft OLE DB Driver for SQL Server
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\msoledbsql.msi"
    state: present
    arguments: "IACCEPTMSOLEDBSQLLICENSETERMS=YES"
  when: version | int >= 11
- name: Looking for .NET Core Runtime in Veeam ISO
  ansible.windows.win_find:
    paths: "{{ source }}Redistr\\x64"
    patterns: dotnet-runtime-.*
    recurse: no
    file_type: file
    use_regex: true
  ignore_errors: yes
  register: file
  when: version | int >= 11
- name: Install Microsoft .NET Core Runtime
  ansible.windows.win_package:
    path: "{{ file.files[0].path }}"
    product_id: Install .NET Core Runtime
    state: present
    arguments: '/install /quiet /norestart /log "{{ destination }}logs\\dotnet-runtime-x.x.x-win-x64.log"'
  when: version | int >= 11
- name: Looking for ASP.NET Core Shared Framework in Veeam ISO
  ansible.windows.win_find:
    paths: "{{ source }}Redistr\\x64"
    patterns: aspnetcore-runtime-.*
    recurse: no
    file_type: file
    use_regex: true
  ignore_errors: yes
  register: file
  when: version | int >= 11
- name: Install Microsoft ASP.NET Core Shared Framework
  ansible.windows.win_package:
    path: "{{ file.files[0].path }}"
    product_id: Install ASP.NET Core Runtime
    state: present
    arguments: '/install /quiet /norestart /log "{{ destination }}logs\\aspnetcore-runtime-x.x.x-win-x64.log"'
  when: version | int >= 11
- name: Install Microsoft Visual C++ Redistributable
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\vc_redist.x64.exe"
    product_id: Install C++ Framework
    state: present
    arguments: '/install /quiet /norestart /log "{{ destination }}logs\\vc_redist.x64.log"'
  ignore_errors: yes
  when: version | int >= 11
- name: Install Microsoft Report Viewer Redistributable
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\ReportViewer.msi"
    state: present
  when: version | int < 11
- name: Install XML Parser
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\msxml6_x64.msi"
    state: present
- name: .NET Framework
  include_tasks: install_net_framework.yml
- name: Enable Windows Feature - IIS Web Server Role
  ansible.windows.win_optional_feature:
    name: IIS-WebServerRole
    state: present
- name: Enable Windows Feature - IIS Web Server
  ansible.windows.win_optional_feature:
    name: IIS-WebServer
    state: present
- name: Enable Windows Feature - IIS Common HTTP Features
  ansible.windows.win_optional_feature:
    name: IIS-CommonHttpFeatures
    state: present
- name: Enable Windows Feature - IIS Windows Authentication Component
  ansible.windows.win_optional_feature:
    name: IIS-WindowsAuthentication
    state: present
- name: Enable Windows Feature - IIS WebSocket Protocol Component
  ansible.windows.win_feature:
    name: Web-WebSockets
    state: present
- name: Enable Windows Feature - .NET Extended support for ASP.NET 4.5
  ansible.windows.win_optional_feature:
    name: NetFx4Extended-ASPNET45
    state: present
- name: Enable Windows Feature - IIS .NET 4.5 Extensibility Component
  ansible.windows.win_optional_feature:
    name: IIS-NetFxExtensibility45
    state: present
- name: Enable Windows Feature - IIS ASP.NET 4.5 Component
  ansible.windows.win_optional_feature:
    name: IIS-ASPNET45
    include_parent: true
    state: present
- name: Enable Windows Feature - IIS Client Certificate Mapping Authentication
  ansible.windows.win_feature:
    name: Web-Client-Auth
    state: present
  when: version | int >= 12
- name: Install Microsoft Application Request Routing
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\requestRouter_amd64.msi"
    state: present
  when: version | int >= 11
- name: Install IIS URL Rewrite Module
  ansible.windows.win_package:
    path: "{{ source }}Redistr\\x64\\rewrite_amd64_en-US.msi"
    state: present
  when: version | int >= 11
