# vbr_patch tasks file for veeamhub.veeam_vas

## PRE-INSTALL TASKS
- name: Including version-specific variables
  include_vars:
    file: "vars/vbr_v{{ version }}.yml"
  when: not (patch | bool)
- name: Setting patch folder (from ISO)
  set_fact:
    patch_folder: "Updates\\"
  when: patch | bool
- name: Setting patch folder (not from ISO)
  set_fact:
    patch_folder: ""
  when: not (patch | bool)
- name: Print Patch Configuration
  debug:
    msg:
      - "ISO Drive Letter: '{{ source }}{{ patch_folder }}{{ patch_file }}'"
      - "Patch Logs Folder: '{{ destination }}logs'"
- name: Create logs directory
  ansible.windows.win_file:
    path: "{{ destination }}logs"
    state: directory
  when: not (patch | bool)
- name: Enable Cloud Connect Maintenance Mode
  veeam_vbr_cloud_connect_maintenance:
    state: enable
  when: cloud_connect | bool
- name: Start adhoc VBR configuration backup job
  veeam_vbr_config_backup:
    state: adhoc
  when: not (patch | bool)
- name: Stopping and disabling all backup jobs
  veeam_vbr_upgrade_job_prep:
    state: disable
    jobs_file: "{{ vbr_jobs_file }}"
  when:
    - not (cloud_connect | bool)
    - not (patch | bool)
  register: jobs
- name: Print Backup Jobs backup file name
  debug:
    var: jobs
  when: not (cloud_connect | bool)
- name: Stopping all Veeam services prior to applying VBR patch
  ansible.windows.win_shell: |
    Stop-Process -Name "Veeam.Backup.Shell" -Force -ErrorAction SilentlyContinue
    Get-Service veeam* | Stop-Service

## INSTALLING PATCH
- name: Install VBR patch
  ansible.windows.win_package:
    path: "{{ source }}{{ patch_folder }}{{ patch_file }}"
    product_id: "Veeam Backup & Replication Update"
    arguments: '/log "{{ destination }}logs\\{{ patch_file }}.log" /silent /noreboot VBR_AUTO_UPGRADE=1'
  register: patch_results

## POST-INSTALL TASKS
- name: Starting all Veeam services
  ansible.windows.win_shell: |
    Get-Service veeam* | Where-Object {$_.Name -ne "VeeamMBPDeploymentService"} | Start-Service
  when: not (patch | bool)
- name: Disable Cloud Connect Maintenance Mode
  veeam_vbr_cloud_connect_maintenance:
    state: disable
  when:
    - cloud_connect | bool
    - not (patch | bool)
- name: Enabling all backup jobs in specified file
  veeam_vbr_upgrade_job_prep:
    state: enable
    jobs_file: "{{ vbr_jobs_file }}"
  when:
    - not (cloud_connect | bool)
    - not (patch | bool)
- name: Stopping all Veeam services (this may take a while)
  ansible.windows.win_shell: |
    if (-Not (Get-Module -ListAvailable -Name Veeam.Backup.PowerShell)){Add-PSSnapin -PassThru VeeamPSSnapIn -ErrorAction Stop | Out-Null}
    Get-VBRJob | Stop-VBRJob | Out-Null
    Get-Service veeam* | Stop-Service
  when: not (patch | bool)
- name: Rebooting server now to complete VBR patch installation
  ansible.windows.win_reboot:
    msg: Reboot initiated by Ansible to complete VBR patch installation
  when:
    - not (patch | bool)
