---
# ONE v10 vars file for veeamhub.veeam_vas

## v10 vars
iso_url: "https://download2.veeam.com/VeeamONE_10.0.2.1094_20200716.iso"
iso_checksum: "b06b91a0d3d757d6bfa504ebff158d7e2339c6874cb7bf1c4d7662820413cfe9"
destination_iso_file: "one.iso"
destination_license_file: "one-license.lic"
sql_express_file: "{{ source }}Redistr\\x64\\SqlExpress\\2016SP2\\SQLEXPR_x64_ENU.exe"
sql_database: "VeeamOne"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
