---
# VBR v10 vars file for veeamhub.veeam_vas

iso_url: "https://download2.veeam.com/VBR/v10/VeeamBackup&Replication_10.0.1.4854_20220304.iso"
iso_checksum: "4810681af5ce592608a7fae5c296419f599f7042"
destination_iso_file: "vbr.iso"
destination_license_file: "vbr-license.lic"
sql_express_file: "{{ source }}Redistr\\x64\\SqlExpress\\2016SP2\\SQLEXPR_x64_ENU.exe"
sql_database: "VeeamBackup"
net_framework_file: "{{ source }}Redistr\\NDP472-KB4054530-x86-x64-AllOS-ENU.exe"
